/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.onlineproductexchange;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.event.MouseEvent;
import static java.awt.image.ImageObserver.HEIGHT;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BoxLayout;
import static javax.swing.GroupLayout.Alignment.CENTER;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import static javax.swing.SwingConstants.LEFT;
import javax.swing.border.EtchedBorder;

/**
 *
 * @author Admin
 */
public class Profile_page extends javax.swing.JFrame {
    
    Color default_color,white,clicked_color;
   String nam,email,mobile_no,department,password;
    
    JLabel buyer_name;
                 JLabel cont;
 String buy_name;
       String contact;
String selectedValue;
int uid;
String name;

public void uid(int u,String n){
uid=u;
//System.out.println(uid);
name=n;

}

public void set_seller_table(){
    
    int pid=0;
Connection dbconn =DBconnection.connectDB();
        if(dbconn!=null){
        try {
            PreparedStatement st2=(PreparedStatement)
                    dbconn.prepareStatement("select * from product where name=?");
            st2.setString(1,jTextField1.getText());
            ResultSet res1=st2.executeQuery();
            if(res1.next()){
                pid=res1.getInt(1);
            }
            
            PreparedStatement st=(PreparedStatement)
                    dbconn.prepareStatement("insert into seller(u_id,seller_name,p_id) values(?,?,?)");
            st.setInt(1,uid);
            st.setString(2,name);
            st.setInt(3,pid);
           
             int res=st.executeUpdate();
         
    }
    catch (SQLException ex){
         Logger.getLogger(OnlineProductExchange.class.getName()).log(Level.SEVERE, null, ex);
    }
    }
    else{
            System.out.println("Connection not available!");
        }

}

    /**
     * Creates new form Profile_page
     */
    public Profile_page() {
       
        initComponents();
        
        default_color=new Color(0,0,0);
        white=new Color(255,255,255);

                  
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel7 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel9 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        jLabel19.setBackground(new java.awt.Color(0, 0, 0));
        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("X");
        jLabel19.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });

        jPanel8.setBackground(new java.awt.Color(0, 0, 0));
        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel10.setBackground(new java.awt.Color(0, 0, 0));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("MY PROFILE");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel10.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 280, 40));

        jPanel11.setBackground(new java.awt.Color(0, 0, 0));

        jLabel4.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("MY ORDERS");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel12.setBackground(new java.awt.Color(0, 0, 0));

        jLabel5.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("MY ITEMS");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel13.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADD A PRODUCT");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        jButton3.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        jButton3.setText("Logout");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton3MouseEntered(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        jButton4.setText("Back to Home!");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton4MouseEntered(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3))
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(191, 191, 191))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 936));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Lucida Bright", 0, 24)); // NOI18N
        jLabel21.setText("Name");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, -1, -1));

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(255, 255, 255));
        jTextField2.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, 390, 40));

        jLabel22.setFont(new java.awt.Font("Lucida Bright", 0, 24)); // NOI18N
        jLabel22.setText("Mobile No.");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 470, -1, -1));

        jLabel23.setFont(new java.awt.Font("Lucida Bright", 0, 48)); // NOI18N
        jLabel23.setText("Profile Details");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 640, 50));

        jLabel24.setFont(new java.awt.Font("Lucida Bright", 0, 24)); // NOI18N
        jLabel24.setText("Department");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 560, -1, -1));

        jLabel26.setFont(new java.awt.Font("Lucida Bright", 0, 24)); // NOI18N
        jLabel26.setText("Password");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, -1, -1));

        jLabel27.setFont(new java.awt.Font("Lucida Bright", 0, 24)); // NOI18N
        jLabel27.setText("Email ID");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, -1, -1));

        jTextField5.setEditable(false);
        jTextField5.setBackground(new java.awt.Color(255, 255, 255));
        jTextField5.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 380, 390, 40));

        jTextField6.setEditable(false);
        jTextField6.setBackground(new java.awt.Color(255, 255, 255));
        jTextField6.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, 390, 40));

        jTextField7.setEditable(false);
        jTextField7.setBackground(new java.awt.Color(255, 255, 255));
        jTextField7.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 550, 390, 40));

        jTextField8.setEditable(false);
        jTextField8.setBackground(new java.awt.Color(255, 255, 255));
        jTextField8.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 460, 390, 40));

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Save");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.setOpaque(true);
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 670, 150, 50));
        jButton5.setVisible(false);

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Edit");
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 669, 150, 50));

        jTabbedPane1.addTab("MyProfile", jPanel1);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1091, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 929, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(jPanel7);

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 945, 630));

        jLabel15.setBackground(new java.awt.Color(0, 0, 0));
        jLabel15.setFont(new java.awt.Font("Lucida Bright", 1, 36)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("MY ITEMS");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 51, 959, -1));

        jTabbedPane1.addTab("Myitems", jPanel5);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane3.setPreferredSize(new java.awt.Dimension(1446, 720));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jScrollPane3.setViewportView(jPanel9);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 950, 650));

        jLabel20.setFont(new java.awt.Font("Lucida Bright", 1, 36)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("MY ORDERS");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 15, 996, 63));

        jTabbedPane1.addTab("MyOrders", jPanel2);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Lucida Bright", 0, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Enter the details of the product");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 818, -1));

        jLabel8.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        jLabel8.setText("Product Name");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 177, -1));

        jTextField1.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        jTextField1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 818, 30));

        jLabel9.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        jLabel9.setText("Description");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 154, -1));

        jLabel10.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        jLabel10.setText("Selling Price/Base-price");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 231, -1));

        jTextField3.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        jTextField3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 818, 30));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jScrollPane1.setViewportView(jTextArea1);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 818, 60));

        jLabel11.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        jLabel11.setText("Product image");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 600, 165, 30));

        jComboBox1.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Electronics", "Books", "Accessories", "Others" }));
        jComboBox1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel4.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 540, 818, 37));

        jLabel12.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        jLabel12.setText("Category");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 500, 165, 30));

        jLabel13.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        jLabel13.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 630, 390, 30));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Select image");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 620, 160, 50));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Submit");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 710, 220, 50));

        jLabel14.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        jLabel14.setText("Years used");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, 231, -1));

        jTextField4.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        jTextField4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, 818, 30));

        jTabbedPane1.addTab("Add a product", jPanel4);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, -44, -1, 980));

        pack();
    }// </editor-fold>//GEN-END:initComponents

           
        
    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
        jPanel12.setBackground(white);
        jLabel5.setForeground(default_color);
        jPanel13.setBackground(default_color);
        jPanel10.setBackground(default_color);
        jPanel11.setBackground(default_color);
        jLabel4.setForeground(white);
        jLabel3.setForeground(white);
        jLabel1.setForeground(white);
//        initializepanel2(uid);
//         initializepanel3(uid);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(3);
        jPanel13.setBackground(white);
        jLabel1.setForeground(default_color);
        jPanel12.setBackground(default_color);
        jPanel10.setBackground(default_color);
        jPanel11.setBackground(default_color);
        jLabel4.setForeground(white);
        jLabel3.setForeground(white);
        jLabel5.setForeground(white);
//        initializepanel2(uid);
//         initializepanel3(uid);
        
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
        jPanel11.setBackground(white);
        jLabel4.setForeground(default_color);
        jPanel13.setBackground(default_color);
        jPanel10.setBackground(default_color);
        jPanel12.setBackground(default_color);
        jLabel5.setForeground(white);
        jLabel3.setForeground(white);
        jLabel1.setForeground(white);
//        initializepanel2(uid);
//         initializepanel3(uid);

    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
        jPanel10.setBackground(white);
        jLabel3.setForeground(default_color);
        jPanel13.setBackground(default_color);
        jPanel12.setBackground(default_color);
        jPanel11.setBackground(default_color);
        jLabel4.setForeground(white);
        jLabel5.setForeground(white);
        jLabel1.setForeground(white);
        jButton5.setVisible(false);
//        initializepanel2(uid);
//         initializepanel3(uid);
        
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
         selectedValue=jComboBox1.getSelectedItem().toString();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser=new JFileChooser();
        chooser.showOpenDialog(null);
        File f=chooser.getSelectedFile();
        filename=f.getAbsolutePath();
        jLabel13.setText(filename);
        try{
        File image=new File(filename);
        FileInputStream fis=new FileInputStream(image);
        ByteArrayOutputStream bos=new ByteArrayOutputStream();
        byte[] buf=new byte[1024];
        for(int readNum;(readNum=fis.read(buf))!=-1;)
        {
        bos.write(buf,0,readNum);
        }
        photo=bos.toByteArray();
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        
        if((jTextField1.getText().isEmpty()) || (jTextField4.getText().isEmpty())||(jTextArea1.getText().isEmpty())||(jTextField3.getText().isEmpty())||(selectedValue==null)){
JOptionPane.showMessageDialog(this,"Please,fill all the details of the product correctly!","Error",JOptionPane.ERROR_MESSAGE);
}
else{
    Connection dbconn =DBconnection.connectDB();
        if(dbconn!=null){
        try {
            PreparedStatement st=(PreparedStatement)
                    dbconn.prepareStatement("insert into product(name,yrs_used,prod_desc,prod_category,price,img) values(?,?,?,?,?,?)");
            st.setString(1,jTextField1.getText());
            st.setString(2,jTextField4.getText());
            st.setString(3,jTextArea1.getText());
            st.setString(4,selectedValue);
            st.setString(5,jTextField3.getText());
            st.setBytes(6,photo);
             int res=st.executeUpdate();
        
            JOptionPane.showMessageDialog(this,"Product added successfully!","Success",JOptionPane.INFORMATION_MESSAGE);
               
            
           
            set_seller_table();
            initializepanel3(uid);
            
            
            
        
    }
    catch (SQLException ex){
         Logger.getLogger(OnlineProductExchange.class.getName()).log(Level.SEVERE, null, ex);
    }
    }
    else{
            System.out.println("Connection not available!");
        }


     
}

        
     
        
    
    }//GEN-LAST:event_jButton2MouseClicked

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        new OnlineProductExchange().setVisible(true);
        
        
    }//GEN-LAST:event_jButton3MouseClicked

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
        jTextField2.setEditable(true);
        jTextField5.setEditable(true);
        jTextField7.setEditable(true);
        jTextField8.setEditable(true);
        jTextField6.setEditable(true);
        
        
        
        jButton5.setVisible(true);
        
        
                jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                
                savebtnclicked(evt);
            }
            
             

            public void savebtnclicked(MouseEvent evt) {
                String name1=jTextField2.getText();
                System.out.println(name1);
        
        String password=jTextField6.getText();
        
        String emailid=jTextField5.getText();
        
        String mobile=jTextField8.getText();
        
        String department=jTextField7.getText();
                Connection dbconn4 =DBconnection.connectDB();
                if(dbconn4!=null){
            try {
                PreparedStatement st9=(PreparedStatement)
                        dbconn4.prepareStatement("Update users set name=?,email=?,dept=?,phoneno=?,password=? where ID=?");
                        st9.setString(1,name1);
                        st9.setString(2,emailid);
                        st9.setString(3,department);
                        st9.setString(4,mobile);
                        st9.setString(5,password);
                        System.out.println("Here is "+uid);
                        String newu=String.valueOf(uid);
                        st9.setString(6,newu);
                        
                        int r=st9.executeUpdate();
                        
                        System.out.println(r);
                        if(r==1){
                            JOptionPane.showMessageDialog(rootPane, " Changes saved!  ", null, INFORMATION_MESSAGE);
                        }
                        else{
                            System.out.println("Not updated!");
                        }
                        
                        
                        
                
            } catch (SQLException ex) {
                Logger.getLogger(Profile_page.class.getName()).log(Level.SEVERE, null, ex);
            }
         }   
            }
                }); 
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseEntered

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        new Home().setVisible(true);


    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4MouseEntered

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed
    public void initializepanel2(int u) {

//         profile panel

        Connection dbconn3 =DBconnection.connectDB();
        if(dbconn3!=null){
        try {
            byte[] imageBytes;
            Image image;
            
            
            
            PreparedStatement st4=(PreparedStatement)
                    dbconn3.prepareStatement("Select * from users where ID=?");
            st4.setInt(1, u);
            ResultSet re=st4.executeQuery();
            while(re.next()){
                
                nam=re.getString(2);
                email=re.getString(3);
                mobile_no=re.getString(5);
                department=re.getString(4);
                password=re.getString(6);
                
            }
            jTextField2.setText(nam);
                jTextField6.setText(password);
                jTextField5.setText(email);
                jTextField8.setText(mobile_no);
                jTextField7.setText(department);
            
            
            
            //myorders
            PreparedStatement st3=(PreparedStatement)
                    dbconn3.prepareStatement("Select * from product natural join bidding where u_id=?");
            
                    st3.setInt(1,u);
            
        
            ResultSet res=st3.executeQuery();
            jPanel9.setLayout(new GridLayout(10,2,25,25));          
                 while(res.next()){
                imageBytes=res.getBytes(7);
                image=getToolkit().createImage(imageBytes);
               
//                ImageIcon icon=new ImageIcon(image);
                JPanel p=new JPanel();
                
                 
//                 String text="Product name: "+res.getString(2)+"\nDescription: "+res.getString(4)+"\nBase-Price: "+res.getInt(6)+"\nYears used: "+res.getInt(3);
                String name="Product name: "+res.getString(2);
                String desc="Description: "+res.getString(4);
                int bp=res.getInt(6);
                String baseprice="Base-Price: "+res.getInt(6);
                String yrs="Years used: "+res.getInt(3);
                String pid=res.getString(1);
                JLabel namelabel=new JLabel(name);
                JTextArea desclabel=new JTextArea(desc,3,6);
                
                desclabel.setEditable(false);
                desclabel.setLineWrap(true);
                desclabel.setWrapStyleWord(true);
              
                desclabel.setBorder(null);
                desclabel.setBackground(Color.white);
                JLabel plabel=new JLabel(baseprice);
                JLabel yrslabel=new JLabel(yrs);
                
                String bidp="Bid-Price: "+res.getString(10);
                JLabel bidlabel=new JLabel(bidp);
                
                p.setLayout(new BoxLayout(p,BoxLayout.Y_AXIS));
                p.setPreferredSize(new Dimension(360, 360));
                ImageIcon imageIcon = new ImageIcon(new ImageIcon(image).getImage().getScaledInstance(360, 200, Image.SCALE_SMOOTH));
                 desclabel.setMinimumSize(new Dimension(p.getWidth(), HEIGHT));
                 JLabel label=new JLabel(imageIcon);
                namelabel.setSize(p.getWidth(), HEIGHT);
                namelabel.setHorizontalAlignment(LEFT);
                
                 p.add(label);
                 
                 p.add(namelabel);
                 
                 p.add(plabel);
                 p.add(yrslabel);
                 p.add(bidlabel);
                 p.add(desclabel);
                 EtchedBorder border=new EtchedBorder(EtchedBorder.RAISED);
                 p.setBorder(border);
                 p.setBackground(Color.white);
                 Font f1,f2;
                f1 = new Font("Lucida Bright",Font.PLAIN,18);
                f2 = new Font("Lucida Bright",Font.BOLD,18);
                 namelabel.setFont(f1);
                 desclabel.setFont(f1);
                 yrslabel.setFont(f1);
                 plabel.setFont(f1);
                 bidlabel.setFont(f1);
      
                 jPanel9.add(p);
                
                
            }
            
            
        
    }
    catch (SQLException ex){
         Logger.getLogger(OnlineProductExchange.class.getName()).log(Level.SEVERE, null, ex);
         
    }
        }
    else{
            System.out.println("Connection not available!");
        }
    }
    public void initializepanel3(int u) {
      
        
//        Myitems panel
        
        Connection dbconn3 =DBconnection.connectDB();
        if(dbconn3!=null){
        try {
            byte[] imageBytes;
            Image image;
            PreparedStatement st3=(PreparedStatement)
                    dbconn3.prepareStatement("Select * from product natural join seller where u_id=?");
            
                    st3.setInt(1,u);
            
        
            ResultSet res=st3.executeQuery();
            jPanel7.setLayout(new GridLayout(10,2,25,25));
            while(res.next()){
                imageBytes=res.getBytes(7);
                image=getToolkit().createImage(imageBytes);
               
//                ImageIcon icon=new ImageIcon(image);
                JPanel p=new JPanel();
                
                 
//                 String text="Product name: "+res.getString(2)+"\nDescription: "+res.getString(4)+"\nBase-Price: "+res.getInt(6)+"\nYears used: "+res.getInt(3);
                String name="Product name: "+res.getString(2);
                String desc="Description: "+res.getString(4);
                int bp=res.getInt(6);
                String baseprice="Base-Price: "+res.getInt(6);
                String yrs="Years used: "+res.getInt(3);
                String pid=res.getString(1);
                JLabel namelabel=new JLabel(name);
                JTextArea desclabel=new JTextArea(desc,3,6);
                
                desclabel.setEditable(false);
                desclabel.setLineWrap(true);
                desclabel.setWrapStyleWord(true);
              
                desclabel.setBorder(null);
                desclabel.setBackground(Color.white);
                JLabel plabel=new JLabel(baseprice);
                JLabel yrslabel=new JLabel(yrs);
                
                p.setLayout(new BoxLayout(p,BoxLayout.Y_AXIS));
                p.setPreferredSize(new Dimension(360, 360));
                ImageIcon imageIcon = new ImageIcon(new ImageIcon(image).getImage().getScaledInstance(360, 200, Image.SCALE_SMOOTH));
                 desclabel.setMinimumSize(new Dimension(p.getWidth(), HEIGHT));
                 JLabel label=new JLabel(imageIcon);
                namelabel.setSize(p.getWidth(), HEIGHT);
                namelabel.setHorizontalAlignment(LEFT);
                
                 p.add(label);
                 p.add(namelabel);
                 
                 p.add(plabel);
                 p.add(yrslabel);
                 p.add(desclabel);
                 EtchedBorder border=new EtchedBorder(EtchedBorder.RAISED);
                 p.setBorder(border);
                 p.setBackground(Color.white);
                 Font f1,f2;
                f1 = new Font("Lucida Bright",Font.PLAIN,18);
                f2 = new Font("Lucida Bright",Font.BOLD,18);
                 namelabel.setFont(f1);
                 desclabel.setFont(f1);
                 yrslabel.setFont(f1);
                 plabel.setFont(f1);
                 JButton finalize_bid=new JButton("Finalize Now!");
                 JButton remove_prod=new JButton("Remove product!");
                 finalize_bid.setBackground(Color.black);
                 finalize_bid.setForeground(Color.white);
                  remove_prod.setBackground(Color.black);
                 remove_prod.setForeground(Color.white);
                 finalize_bid.setFont(f2);
                 remove_prod.setFont(f2);
                 p.add(finalize_bid);
                 p.add(remove_prod);
                 namelabel.setFont(f1);
                 desclabel.setFont(f1);
                 yrslabel.setFont(f1);
                 plabel.setFont(f1);
                 
                 remove_prod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                try {
                    remove_btn_clicked(evt);
                } catch (SQLException ex) {
                    Logger.getLogger(Profile_page.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            public void remove_btn_clicked(MouseEvent evt) throws SQLException {
                        PreparedStatement st12=(PreparedStatement)
                    dbconn3.prepareStatement("delete from product where p_id=?");
                        st12.setString(1,pid);
                        
                    int res12=st12.executeUpdate();
                    JOptionPane.showMessageDialog(rootPane, "Product removed!  ", null, INFORMATION_MESSAGE);
                    }
                    
                });
                 
                 PreparedStatement st10=(PreparedStatement)
                    dbconn3.prepareStatement("Select * from purchaser where p_id=?");
            
                    st10.setString(1,pid);
                  
            
        
            ResultSet res10=st10.executeQuery();
              if(res10.next()){
               p.remove(finalize_bid);
                        buyer_name=new JLabel(buy_name);
                cont=new JLabel(contact);
                 p.add(buyer_name);
                 p.add(cont);
              }
    
                 
                 
                 
                
                       
               
                 
                      finalize_bid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                try {
                    finalizebtnclicked(evt);
                } catch (SQLException ex) {
                    Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

                    private void finalizebtnclicked(MouseEvent evt) throws SQLException {
                        
                    Connection dbconn =DBconnection.connectDB();
        if(dbconn!=null){
        try {
            PreparedStatement st4=(PreparedStatement)
                    dbconn.prepareStatement("select * from bidding where bid_price=(select max(bid_price) from bidding where p_id=?)");
            st4.setString(1,pid);
           
             ResultSet res4=st4.executeQuery();
             if(res4.next()){
                 int bidp=res4.getInt(2);
                 int user_id=res4.getInt(3);
//                 System.out.println(user_id+"        jgdflkjgd");
                 int prod_id=res4.getInt(4);
             PreparedStatement st5=(PreparedStatement)
                    dbconn.prepareStatement("insert into purchaser(quoted_price,u_id,p_id) values(?,?,?)");
            st5.setInt(1,bidp);
            st5.setInt(2,user_id);
            st5.setInt(3,prod_id);
            
            int res5=st5.executeUpdate();
            
            PreparedStatement st12=(PreparedStatement)
                    dbconn.prepareStatement("UPDATE product set status=? where p_id=?");
            st12.setString(1,"sold");
            st12.setInt(2,prod_id);
            int res12=st12.executeUpdate();
            
            PreparedStatement st6=(PreparedStatement)
                    dbconn.prepareStatement("select * from users where ID=?");
            st6.setInt(1, user_id);
            
            ResultSet res6=st6.executeQuery();
            if(res6.next()){
                buy_name="Purchaser Name:"+res6.getString(2);
                contact="Purchaser Contact Number:"+res6.getString(5);  
            }
            
            String bidpppp="Bid Amount:"+bidp;
            
            JOptionPane.showMessageDialog(rootPane, " Product sold!  "+buy_name+"\n"+contact+"\n"+bidpppp, null, INFORMATION_MESSAGE);
            
            remove_finalize_btn();
             }
             else{
             JOptionPane.showMessageDialog(rootPane, "This product is not bid yet,Please wait until someone bids!", null, ERROR_MESSAGE);
             }
    }
    catch (SQLException ex){
         Logger.getLogger(OnlineProductExchange.class.getName()).log(Level.SEVERE, null, ex);
    }
    }
    else{
            System.out.println("Connection not available!");
        }
        
                    
                
                    }

                    public void remove_finalize_btn() {
                        p.remove(finalize_bid);
                        buyer_name=new JLabel(buy_name);
                cont=new JLabel(contact);
                 p.add(buyer_name);
                 p.add(cont);
                    }

                    private void remove_btn_clicked(MouseEvent evt) {
                        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
                    }
        });
              jPanel7.add(p);  
            }
            
            
        
    }
    catch (SQLException ex){
         Logger.getLogger(OnlineProductExchange.class.getName()).log(Level.SEVERE, null, ex);
         
    }
        }
    else{
            System.out.println("Connection not available!");
        }
    
    }
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Profile_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Profile_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Profile_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Profile_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Profile_page().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
byte[] photo=null;
String filename=null;

}
